#include "OutputContainer.hpp"
OutputContainer::OutputContainer(const KFParticle& particle,
                                 std::array<float, 3> decay_point,
                                 std::array<float, 3> decay_point_err) : daughter_ids_(particle.DaughterIds()),
                                                                         px_(particle.GetPx()),
                                                                         py_(particle.GetPy()),
                                                                         pz_(particle.GetPz()),
                                                                         mass_(particle.GetMass()),
                                                                         pdg_(particle.GetPDG()),
                                                                         pt_error_(particle.GetErrPt()),
                                                                         phi_error_(particle.GetErrPhi()),
                                                                         eta_error_(particle.GetErrEta()),
                                                                         mass_error_(particle.GetErrMass()),
                                                                         x_decay_(decay_point.at(0)),
                                                                         y_decay_(decay_point.at(1)),
                                                                         z_decay_(decay_point.at(2)),
                                                                         x_decay_error_(decay_point_err.at(0)),
                                                                         y_decay_error_(decay_point_err.at(1)),
                                                                         z_decay_error_(decay_point_err.at(2)),
                                                                         x_pca_(particle.GetX()),
                                                                         y_pca_(particle.GetY()),
                                                                         z_pca_(particle.GetZ()),
                                                                         x_pca_error_(particle.GetErrX()),
                                                                         y_pca_error_(particle.GetErrY()),
                                                                         z_pca_error_(particle.GetErrZ()) {}
